services:
  todo-api:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      todo-db:
        condition: service_healthy
      todo-redis:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
      
  todo-db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: todo-db
      POSTGRES_USER: todo-admin
      POSTGRES_PASSWORD: admin123
    volumes:
      - todo-db-data:/var/lib/postgresql/data
    ports:
      - "5430:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U todo-admin -d todo-db"]
      interval: 5s
      timeout: 5s
      retries: 5
  todo-redis:
    image: redis
    restart: always
    ports:
      - '6370:6379'
    healthcheck:
        test: ["CMD", "redis-cli", "ping"]
        interval: 30s
        timeout: 10s
        retries: 5
volumes:
  todo-db-data: